# -*- coding: utf-8 -*-
"""prediksi_co2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1afOu8kgF3dOoxEv9VZY9IXghj5L2c3VU
"""

import pickle
import streamlit as st 
import pandas as pd
import matplotlib.pyplot as plt

model = pickle.load(open('prediksi_co2.sav', 'rb'))

df = pd.read_excel("CO2 dataset.xlsx")
df['Year'] = pd.to_datetime(df['Year'], format='%Y')
df.set_index(['Year'], inplace=True)

df['CO2'] = pd.to_numeric(df['CO2'], errors='coerce')

st.title('Forecasting CO2')
year = st.slider("Tentukan Tahun",1,30,step = 1)

pred = model.forecast(year)
pred = pd.DataFrame(pred, columns=['CO2'])

if st.button("Predict"):

        col1, col2 = st.columns([2,3])
        with col1:
             st.dataframe(pred)
        with col2:
            fig, ax = plt.subplots()
            df['CO2'].plot(style='--', color='gray', legend=True, label='known')
            pred['CO2'].plot(color='b', legend=True, label='prediction')
            st.pyplot(fig)
